# Generated by Django 4.2.7 on 2026-01-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='bookmarkFlag',
        ),
    ]
