# Generated by Django 5.2.3 on 2026-01-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_bookmark_bookmarkflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
