# Generated by Django 5.2.3 on 2026-07-09 04:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_reaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reading_time_minutes',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(db_index=True, default='general', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='draft',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddIndex(
            model_name='highlight',
            index=models.Index(fields=['post', 'user'], name='idx_highlight_post_user'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['user', '-viewed_at'], name='idx_history_user_viewed'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['draft', 'category'], name='idx_post_draft_category'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['draft', '-views'], name='idx_post_draft_views'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['draft', '-timestamp'], name='idx_post_draft_timestamp'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['post', 'type'], name='idx_reaction_post_type'),
        ),
    ]
