# Generated by Django 5.2.3 on 2026-05-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customuser_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='theme_preference',
            field=models.CharField(default='ocean', max_length=20),
        ),
    ]
