# Generated by Django 5.2.3 on 2026-05-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customuser_theme_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='social_profile_completed',
            field=models.BooleanField(default=True),
        ),
    ]
